language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
before_install:
 - gem install nokogiri -- --with-cflags='--std=gnu99'
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec